; 206528275, 50%
; 315181537, 50%
.ORIG X4190
TriangleInequality:

ST R7, LABEL7
ST R4, LABEL4 ;THIS REGISTER WILL HELP US COMPARE THE ADD RESULTS
LD R3, ERROR 
; CASE1: ONE OR BOTH OF THE REGISTERS <0 
ADD R0, R0, #0
BRn FINISH 
ADD R1, R1, #0
BRn FINISH 
ADD R2, R2, #0
BRn FINISH 
; IF RECHED HERE THEN ALL VALUES >=0
ADD R3, R3, #1 ;R3=0
;CHECK IF R0+R1>=R2
ADD R4, R0, R1

NOT R4, R4     ;CONVERT R4 TO NEGATIVE IN ORDER TO DO THE MINUS OPERATION----? R2-R4
ADD R4, R4, #1 

ADD R4, R4, R2 
BRp FINISH ;IN CASE THE RESULT IS POSITIVE, IT MEANS THAT R2 IS BIGGER THAN THE ADDITION OF OTHER REGISTERS
;CHECK IF R0+R2>=R1
ADD R4, R0, R2

NOT R4, R4     ;CONVERT R4 TO NEGATIVE IN ORDER TO DO THE MINUS OPERATION----? R1-R4
ADD R4, R4, #1 

ADD R4, R4, R1 
BRp FINISH ;IN CASE THE RESULT IS POSITIVE, IT MEANS THAT R1 IS BIGGER THAN THE ADDITION OF OTHER REGISTERS
;CHECK IF R1+R2>=R0
ADD R4, R1, R2

NOT R4, R4     ;CONVERT R4 TO NEGATIVE IN ORDER TO DO THE MINUS OPERATION----? R0-R4
ADD R4, R4, #1 

ADD R4, R4, R0 
BRp FINISH ;IN CASE THE RESULT IS POSITIVE, IT MEANS THAT R0 IS BIGGER THAN THE ADDITION OF OTHER REGISTERS

;IF RECHED HERE, THEN ALL THE REGISTERS DO INFACT REPRESENT THE TriangleInequality
ADD R3, R3, #1 ; R3=1

FINISH:
LD R7, LABEL7
LD R4, LABEL4
RET

LABEL7 .FILL #0	
LABEL4 .FILL #0	
ERROR .FILL #-1	
; Put your various labels here, between RET and .END.
; Remember to write comments that thoroughly explain everything you do - this is assembly code, not Python or C! It's hard to follow otherwise.	

; Make sure to properly write your real ID at the top of this asm file, don't just leave the default values there!
.END
